### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by levinjoller** [levinjoller/Kajava#2]

**Comment by vishalsingh2972** [comment]
@levinjoller can you assign this to me I would like to work on this!

**Comment by levinjoller** [comment]
@vishalsingh2972 Sure, why not. Thanks for helping me.

**Comment by levinjoller** [comment]
@vishalsingh2972 Thank you.

**Comment by levinjoller** [comment]
@vishalsingh2972 Thank you.
